Algoritmo "Exercicio20"
// Disciplina   : [Linguagem e Lógica de Programação]
//  
// Descrição   : Verificar multiplo de 2 com enquant
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/10/2022
Var
j,num:inteiro


Inicio
 escreval("Digite um numero: ")
leia(num)
j<-1
enquanto j=1 faca
se(num%2=0)entao
escreval(num, " é multiplo de 2")
j<-2
senao
escreval("Digite um numero: ")
leia(num)
fimse
fimenquanto
Fimalgoritmo