Algoritmo "Exercicio23"
// Disciplina   : [Linguagem e Lógica de Programação]
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/11/2022
Var
j,i:inteiro

Inicio
escreval("imprimindo de 1 a 10 repita ate: ")
j<-1
repita
escreval(j)
j<-j+1
se j=5 entao
interrompa
fimse
ate j>10
escreval("Executando apos um interrompa j = ",j)

Fimalgoritmo