Algoritmo "Exercicio16"
// Disciplina   : [Linguagem e Lógica de Programação]
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/10/2022
Var
j,num1,num2:inteiro

Inicio
escreva("Primeiro numero: ")
leia(num1)
escreva("Segundo numero: ")
leia(num2)
para j de num1 ate num2 faca
se (j%3=0)entao
escreval(j)
fimse
fimpara
Fimalgoritmo