Algoritmo "Exercicio27"
// Disciplina   : [Linguagem e Lógica de Programação]
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/11/2022
Var
alunos:vetor[1..3]de caracter;
i:inteiro

Inicio
para i<-1 ate 3 faca
escreva("Digite o nome do ",i,"º aluno: ")
leia(alunos[i])
fimpara
para i<-1 ate 3 faca
escreval("Nome do ",i,"º aluno: ",alunos[i])
fimpara

Fimalgoritmo